years = ["550 BCE", "1350", "1600s", "1800s", "1950"]
image_paths = ['550 BCE.png', '1350.png', '1600s.png', '1800s.png', '1950.png']
paragraphs = [
    '''        The period succeeding the year 550 BCE approximates the beginning of mathematics in Greece and the age of philosophy. It also heralds the lives of figures such as Pygathoras, Plato, Euclid, and Archimedes, pioneering the introduction of the basic concepts of geometry, trigonometry, and astronomy through various works such as The Elements. In addition, the concept of Pygathoreanism was introduced to select individuals, creating a culture that highly glorified mathematics ⎯ treating it, in essence, as the predominant force in the universe ⎯ that became secluded and separated from the masses.
        Just as math is new and unfamiliar during this period, human infancy is similarly secluded. The child has just been introduced to the world and is often held at high importance; they are frequently viewed as the center of the universe, by their parents due to the vanity of love, and by themselves because they lack the development necessary to differentiate themselves from their surroundings. Furthermore, infants often create standards and means of conveying their intentions that only their parents understand due to the child’s lack of verbal communication, similar to how those who practiced Pygathoreanism were highly secretive, and how mathematics was only available and understood by a handful of individuals.
''', '''        During the mid-14th century, Arab mathematicians began to construct mathematical equations solely of abstract symbols, thereupon distinguishing themselves from the orthodox majority of society at the time, setting in stone the archetypes of mathematical notation, and creating the concept of standard symbolic notation, which would continue to be the universal representation of the mathematical equations so commonly seen in education systems for centuries onwards.
        Similarly, during the early childhood stage of a human, general verbal and written language is introduced to establish standards, providing them with the newfound ability to communicate with their surroundings and the outside world. Furthermore, childhood is generally also the stage during which amenities and moral beliefs are established by adult guardians, shaping the child into a generally acceptable individual by the population and enabling them to become acquainted with a larger group of peers, just as mathematics became more widely known, understood, and practiced by the general populace as they continued the spread and discovery of knowledge. Just as the symbols of mathematics stand to represent pillars of growth and a new era of discovery, the literacy introduced in early life continues to fuel the evolution of a child’s soul. By giving them the tools to grow their knowledge and curiosity, individuals are given the opportunity to flourish into endless possibilities.
''', '''        The 17th century was known as the “golden century” of mathematics due to massive advances that occurred in various subject sectors. It marks the age of Sir Isaac Newton, Pierre de Fermat, and Blaise Pascal, and encompasses the development of trigonometry, analytic geometry, and calculus, among others. It also proclaims the development of “invisible colleges”, where collections of mathematicians gathered together to collaborate on studies and research, accelerating the process of discovery and innovation exponentially.
        Just as the 17th century made major contributions towards the development of mathematics, the youth of a human brings similar advancements. It is the period in which the bulk of their information and education is delivered to them, and the age at which they are most susceptible to new knowledge. Youth therefore serves as one of the most productive periods for the child to learn within the bounds of society and develop under the public’s expectations, and also where children often develop some of the deepest bonds possible while remaining in the education system, similar to the cooperation of various mathematicians in this era. To relive one's youth is sought after by all for rightful reason, as it holds most of the lasting memories that individuals will ever make.
''', '''        During the early 19th century, non-Euclidean geometry is developed separately by Carl Friedrich Gauss, Nikolay Lobachevsky, and Bernhard Riemann, creating an entirely new branch of geometry. Non-Euclidean geometry was based on the concept of the curvature of space, which was theorized to contain a “non-Euclidean plane” on which the axioms that Euclid presented in his work ‘The Elements’; that is, lines and shapes would no longer follow the previously established expectations. Thus, mathematics was no longer bound by the orthodox restrictions that past mathematicians had set and followed, and mathematicians were able to explore areas that had never before been discovered.
        The sense of scrutiny and exploration is similar to the adolescence of a human, in which individuals are often rebellious and willingly, if not ecstatically, explore beyond the bounds of what has been taught to them as “right”. It is also the stage in which teenage individuals and young adults expand their reach of knowledge and experience and decide on what they want to be in the future, similar to how non-Euclidean geometry expanded on the previously established Euclidean geometry with a new perspective. Adolescence provides developing adults with the time to explore who they truly are and present new journeys and untrodden paths for them to follow.
''', '''        During the mid-19th century, computer technology and artificial intelligence began developing at a highly accelerated rate. It was at this time that figures such as Alan Turing, Arthur Samuel, and John McCarthy began taking interest in the topic, leading to massive expansion and development in the industry. A period of frequent breakthroughs and innovations followed in 1980. The technology is still prevalent in the present day, and remains one of the most impactful innovations in modern society, providing a simple and efficient venue in various fields, for better or for worse. What’s more important, it seems, is the technology’s insecurity: the prospect of a platform that provides “anonymous sending” also gives many people the ability to impersonate and misinform, and one wonders why people are so insistent to support what is obviously a very unstable concept.
        This is similar to the stage of adulthood, where most decisions may have a lasting effect on an individual’s life: the choices do not have a foreseen outcome and hold a high level of uncertainty, similar to how the still-developing world of AI can lead to uncertain results. Identity and relationships are also less emphasized, as people are frequently working and often no longer have the time to explore or develop their personality due to the highly competitive environment, similar to how the new technology creates an identity for individuals that may be different from who they truly are.
'''
]